require('./sqlite-env');
const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
Object.assign(process.env,{BUYER_ACCOUNT_FLOW:'true',PAYMENT_PROVIDER:'mock',DATABASE_PATH:path.resolve(__dirname,'../.test-runs/account-browser-'+crypto.randomUUID()+'.sqlite'),SUPABASE_URL:'https://auth.invalid',SUPABASE_ANON_KEY:'fixture',SUPABASE_SERVICE_ROLE_KEY:'fixture-service'});
let uid;const realFetch=global.fetch;
global.fetch=async(url,options)=>{if(!String(url).startsWith('https://auth.invalid'))return realFetch(url,options);return Response.json(url.endsWith('/user')?{id:uid,email:'buyer@example.test'}:{access_token:'fixture',user:{id:uid,email:'buyer@example.test'}});};
const {app}=require('../server'),db=require('../db/database'),{chromium}=require('../.test-runs/browser/node_modules/playwright');let browser,server;
(async()=>{await db.initDb();server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;process.env.PUBLIC_APP_URL=base;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const width of [320,375,390,430,1280]){
  uid=crypto.randomUUID();const context=await browser.newContext({viewport:{width,height:850}}),page=await context.newPage();
  await page.goto(base);await page.locator('#ageConfirm').click();await page.evaluate(()=>openCheckout('monthly'));
  await page.locator('#pixActiveArea').waitFor({state:'visible'});assert.equal(await page.locator('#checkoutClientForm').isVisible(),false);
  const pending=await page.evaluate(()=>JoiceCheckouts.selected());
  await require('../services/entitlements').confirmPayment(pending.payment.orderId);
  const before=(await require('../services/conversions').summary()).products.find(p=>p.id==='monthly');assert.equal(before.awaitingClaim,1);
  await page.waitForURL(/\/criar-acesso(?:\?|$)/);await page.locator('#accountForm').waitFor({state:'visible'});
  assert.equal(await page.locator('#accountForm input:enabled').count(),4);
  await page.screenshot({path:path.resolve(__dirname,'../.test-runs/account-signup-'+width+'.png')});
  await page.locator('[name=email]').fill('buyer'+width+'@example.test');await page.locator('[name=phone]').fill('11999990000');await page.locator('[name=password]').fill('test-password');await page.locator('[name=confirmPassword]').fill('test-password');await page.locator('#submit').click();
  await page.waitForURL('**/meu-acesso');await page.getByRole('button',{name:'Entrar no VIP'}).waitFor();const after=(await require('../services/conversions').summary()).products.find(p=>p.id==='monthly');assert.equal(after.awaitingClaim,0);assert.equal(after.linked,before.linked+1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:path.resolve(__dirname,'../.test-runs/account-access-'+width+'.png')});
  await page.getByRole('button',{name:'Entrar no VIP'}).click();await page.waitForURL('**/vip');await page.locator('#vipContent').waitFor({state:'visible'});
  await page.goto(base+'/meu-acesso');await page.getByText('Sair da conta',{exact:true}).click();await page.waitForURL('**/login');
  await page.locator('[name=email]').fill('buyer'+width+'@example.test');await page.locator('[name=password]').fill('test-password');await page.locator('#submit').click();await page.waitForURL('**/meu-acesso');
  await page.goto(base+'/esqueci-senha');await page.locator('#accountForm').waitFor({state:'visible'});assert.equal(await page.locator('#accountForm input:enabled').count(),1);
  console.log('PASS accounts mobile '+width+': no prepayment form, paid signup, account, VIP, logout/login, recovery layout');await context.close();
 }
 process.env.BUYER_ACCOUNT_FLOW='false';
 const legacyToken=crypto.randomBytes(32).toString('hex');
 const legacy=await require('../services/orders').createOrder(require('../products').monthly,legacyToken,'mock',{phone:'11999990000'});
 await require('../services/orders').updateOrderPayment(legacy.public_id,await require('../payments/mock-provider').createPixPayment({orderId:legacy.public_id}));
 await require('../services/entitlements').confirmPayment(legacy.public_id);
 process.env.BUYER_ACCOUNT_FLOW='true';
 const legacyContext=await browser.newContext(),legacyPage=await legacyContext.newPage();
 await legacyPage.goto(base+'/vip#o='+legacy.public_id+'&t='+legacyToken);
 await legacyPage.locator('#vipContent').waitFor({state:'visible'});
 console.log('PASS existing paid purchase retains authorized VIP after account rollout');
 await legacyContext.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}global.fetch=realFetch;await db.closeDb();});
