require('./sqlite-env');
const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
Object.assign(process.env,{BUYER_ACCOUNT_FLOW:'true',PAYMENT_PROVIDER:'mock',WHATSAPP_NUMBER:'5511999990000',DATABASE_PATH:path.resolve(__dirname,'../.test-runs/reload-'+crypto.randomUUID()+'.sqlite')});
const {app}=require('../server'),db=require('../db/database'),{chromium}=require('../.test-runs/browser/node_modules/playwright');
let server,browser;
(async()=>{
 await db.initDb();server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base='http://127.0.0.1:'+server.address().port;process.env.PUBLIC_APP_URL=base;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({viewport:{width:390,height:850}});let charges=0;
 page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/payments/pix'))charges++;});
 let dropped=false;
 await page.route('**/api/payments/pix',async route=>{if(dropped)return route.continue();dropped=true;await route.fetch();await route.abort('connectionfailed');});
 await page.goto(base);await page.locator('#ageConfirm').click();await page.locator('#btnPlan1m').click();await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await page.locator('#pixActiveArea').waitFor({state:'visible'});
 const first=await page.evaluate(()=>JSON.stringify(JoiceCheckouts.selected()));assert.equal(charges,2);
 await page.reload();await page.waitForFunction(()=>typeof openCheckout==='function');
 assert.equal(await page.locator('#checkoutModalOverlay').evaluate(e=>e.classList.contains('open')),false);
 assert.equal(charges,2);assert.equal(await page.evaluate(()=>JSON.stringify(JoiceCheckouts.selected())),first);
 await page.locator('#pixNotificationBell').waitFor({state:'visible'});
 await page.locator('#pixNotificationBell').click();await page.locator('#pixNotificationContinue').click();await page.locator('#pix').waitFor({state:'visible'});assert.equal(charges,2,'notification reuses the same PIX');
 await page.goto(base+'/?buy=whatsapp_unlock');await page.locator('#pixActiveArea').waitFor({state:'visible'});
 assert.equal(new URL(page.url()).searchParams.has('buy'),false);assert.equal(charges,3);
 await page.reload();await page.waitForFunction(()=>typeof openCheckout==='function');
 assert.equal(await page.locator('#checkoutModalOverlay').evaluate(e=>e.classList.contains('open')),false);assert.equal(charges,3);
 await page.locator('#pixNotificationBell').waitFor({state:'visible'});
 await page.evaluate(()=>history.replaceState(null,'','/?buy=whatsapp_unlock'));await page.reload();await page.waitForFunction(()=>typeof openCheckout==='function');
 assert.equal(await page.locator('#checkoutModalOverlay').evaluate(e=>e.classList.contains('open')),false);assert.equal(charges,3);
 assert.equal((await (await db.getDb()).get('SELECT COUNT(*) n FROM orders')).n,2);
 const pending=await page.evaluate(()=>JoiceCheckouts.selected());
 await require('../services/entitlements').confirmPayment(pending.payment.orderId);
 await page.reload();await page.locator('#pixNotificationBell').waitFor({state:'visible'});
 await page.locator('#pixNotificationBell').click();assert.match(await page.locator('#pixNotificationPanel').textContent(),/Pagamento confirmado/);
 assert.equal(await page.getByRole('button',{name:'Criar meu acesso',exact:true}).count(),1);
 assert.equal(charges,3);
 console.log('PASS: lost response retries same order; monthly/contact reload stays closed; pending claim preserved; explicit retry reuses PIX; contact link consumed; no extra charges');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await db.closeDb();});
