require('./sqlite-env');
const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
Object.assign(process.env,{DATABASE_PATH:path.resolve(__dirname,'../.test-runs/tips-'+crypto.randomUUID()+'.sqlite'),PAYMENT_PROVIDER:'syncpay',BUYER_ACCOUNT_FLOW:'true',SYNCPAY_CLIENT_ID:'tip-fixture',SYNCPAY_CLIENT_SECRET:'tip-fixture-secret',SYNCPAY_WEBHOOK_SECRET:'tip-webhook-fixture'});
const realFetch=global.fetch,calls=[];
global.fetch=async(url,options)=>{if(String(url).startsWith('http://127.0.0.1:'))return realFetch(url,options);assert.ok(String(url).startsWith('https://api.syncpayments.com.br/api/partner/v1/'));const body=JSON.parse(options.body);if(url.endsWith('/auth-token'))return Response.json({access_token:'fixture',expires_in:3600});assert.deepEqual(Object.keys(body),['amount']);calls.push(body.amount);return Response.json({identifier:crypto.randomUUID(),pix_code:'TEST-NOT-PAYABLE'});};
const {app}=require('../server'),database=require('../db/database'),catalog=require('../products'),tip=Object.values(catalog).find(p=>p.type==='tip');let server;
(async()=>{await database.initDb();server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,db=await database.getDb();
 const resolver=require('../services/tips');for(const v of [undefined,null,499,-500,500.5,'500',1000001,NaN,Infinity])assert.throws(()=>resolver.resolve(tip,v));assert.equal(resolver.resolve(tip,537).price,5.37);
 const token=crypto.randomBytes(32).toString('hex');
 async function create(cents,extra={}){const r=await fetch(base+'/api/payments/pix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:tip.id,tipAmountCents:cents,checkoutToken:token,...extra})});return {status:r.status,body:await r.json()};}
 assert.equal((await create(499)).status,400);
 const created=await create(537,{amount:999,client:{name:'never send',phone:'11999990000'}});assert.equal(created.status,201);assert.equal(created.body.product.price,5.37);assert.equal(created.body.accountFlow,false);
 assert.equal((await create(537)).body.orderId,created.body.orderId);assert.equal((await create(600)).status,409);assert.deepEqual(calls,[5.37]);
 const row=await db.get('SELECT * FROM orders WHERE public_id=?',created.body.orderId);assert.equal(row.purchase_kind,'tip');assert.equal(row.access_type,'tip');assert.equal(row.claim_required,0);assert.equal(row.customer_phone,null);
 async function webhook(amount,invalid=false){const raw=JSON.stringify({event:'transaction.updated',event_id:'tip-fixture-event',transaction:{reference_id:row.provider_payment_id,status:'completed',amount,currency:'BRL',payment_method:'pix'}}),t=Math.floor(Date.now()/1000),sig=crypto.createHmac('sha256',process.env.SYNCPAY_WEBHOOK_SECRET).update(t+'.'+raw).digest('hex');return fetch(base+'/api/webhooks/syncpay',{method:'POST',headers:{'Content-Type':'application/json','X-SyncPay-Event':'transaction.updated','X-SyncPay-Delivery':crypto.randomUUID(),'X-SyncPay-Signature':'t='+t+',v1='+(invalid?'0'.repeat(64):sig)},body:raw});}
 assert.equal((await webhook(5.37,true)).status,401);assert.equal((await webhook(6)).status,409);assert.equal((await webhook(5.37)).status,200);assert.equal((await webhook(5.37)).status,200);
 assert.equal((await db.get('SELECT status FROM orders WHERE id=?',row.id)).status,'PAID');assert.equal((await db.get('SELECT COUNT(*) n FROM entitlements WHERE order_id=?',row.id)).n,0);
 const headers={Authorization:'Bearer '+token};for(const route of ['/api/vip/','/api/contact/','/api/access/'])assert.notEqual((await fetch(base+route+row.public_id,{headers})).status,200);
 const st=await (await fetch(base+'/api/orders/'+row.public_id+'/status',{headers})).json();assert.equal(st.status,'PAID');assert.equal(st.granted,false);assert.equal(st.contactGranted,false);assert.equal(st.needsClaim,false);
 const monthly=Object.values(catalog).find(p=>p.accessDays===30);const normal=await create(500,{productId:monthly.id,checkoutToken:crypto.randomBytes(32).toString('hex'),amount:.01});assert.equal(normal.body.product.price,9.9);
 console.log('PASS tips: cents validation, R$5 minimum, exact SyncPay amount only, no PII, immutable retry amount, signed webhook, mismatch/forgery rejected, duplicate idempotent, no VIP/contact/account grant, subscriptions unchanged');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}global.fetch=realFetch;await database.closeDb();});
