require('./sqlite-env');
const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
Object.assign(process.env,{BUYER_ACCOUNT_FLOW:'true',PAYMENT_PROVIDER:'mock',DATABASE_PATH:path.resolve(__dirname,'../.test-runs/tips-browser-'+crypto.randomUUID()+'.sqlite')});
const {app}=require('../server'),db=require('../db/database'),{chromium}=require('../.test-runs/browser/node_modules/playwright');let server,browser;
(async()=>{await db.initDb();server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;process.env.PUBLIC_APP_URL=base;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const width of [320,375,390,430,1280]){const ctx=await browser.newContext({viewport:{width,height:850}}),p=await ctx.newPage();await p.goto(base);await p.locator('#ageConfirm').click();await p.locator('.profile-actions .tip-trigger').waitFor();assert.ok(await p.locator('.preview-actions .tip-trigger').count()>0);await p.locator('.profile-actions .tip-trigger').click();await p.locator('#tipStatus').filter({hasText:'Carregando'}).waitFor({state:'hidden'});await p.locator('#tipAmount').fill('4,99');await p.locator('#tipGenerate').click();await p.getByText(/Escolha de R\$/).waitFor();await p.locator('#tipAmount').fill('5,37');await p.locator('#tipGenerate').click();await p.locator('#tipPix').waitFor({state:'visible'});assert.match(await p.locator('#tipTotal').innerText(),/5,37/);assert.equal(await p.locator('#tipQr').evaluate(e=>e.complete&&e.naturalWidth>0),true);assert.equal(await p.locator('.tip-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);if(width===390)await p.screenshot({path:path.resolve(__dirname,'../.test-runs/tips-390.png')});await p.locator('.tip-close').click();await p.reload();assert.equal(await p.locator('.tip-dialog').isVisible(),false);await p.locator('.preview-actions .tip-trigger').first().click();await p.locator('#tipPix').waitFor({state:'visible'});await p.locator('#tipSimulate').click();await p.getByText('Mimo recebido! Obrigada pelo carinho ♥',{exact:true}).waitFor();assert.equal(new URL(p.url()).pathname,'/');console.log('PASS tips browser '+width+': top/post buttons, custom amount, QR, explicit resume, no auto popup, simulated confirmation without signup');await ctx.close();}
 const p=await browser.newPage();await p.goto(base);await p.addScriptTag({url:base+'/image-tools.js'});const metrics=await p.evaluate(async()=>{const tools=window.AylaImageTools||window.JoiceImageTools,c=document.createElement('canvas');c.width=3000;c.height=4000;const g=c.getContext('2d'),gradient=g.createLinearGradient(0,0,3000,4000);gradient.addColorStop(0,'#4b6290');gradient.addColorStop(1,'#d6a084');g.fillStyle=gradient;g.fillRect(0,0,3000,4000);const b=await new Promise(r=>c.toBlob(r,'image/png'));const f=new File([b],'test.png',{type:'image/png'}),out=await tools.post(f),img=await createImageBitmap(out),avatar=await tools.profile(f,'avatar');return {bytes:out.size,width:img.width,height:img.height,type:out.type,cached:await tools.post(f)===out,avatarSame:await tools.post(avatar)===avatar,avatarBytes:avatar.size};});assert.equal(metrics.type,'image/webp');assert.ok(metrics.bytes<=450*1024&&Math.max(metrics.width,metrics.height)<=1920);assert.ok(Math.abs(metrics.width/metrics.height-.75)<.002);assert.ok(metrics.cached&&metrics.avatarSame&&metrics.avatarBytes<=25*1024);console.log('PASS optimized upload: WebP, 1920px/450KB ceiling, preserved ratio, stable retry bytes, avatar budget preserved');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await db.closeDb();});
