-- Schema de PRODUÇÃO (PostgreSQL / Supabase).
--
-- Mesmas tabelas e colunas do schema.sql (SQLite): o código não muda, só o
-- lugar onde os dados ficam. Timestamps são `timestamp` (sem timezone) e
-- guardam UTC, exatamente como o SQLite fazia — é o que mantém as compa-
-- rações de data e o formato das strings idênticos entre os dois bancos.

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id TEXT UNIQUE NOT NULL,
  product_id TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  currency TEXT NOT NULL DEFAULT 'BRL',
  status TEXT NOT NULL DEFAULT 'PENDING',
  payment_provider TEXT,
  provider_payment_id TEXT,
  pix_copy_paste TEXT,
  checkout_hash TEXT,
  pix_qr_code TEXT,
  webhook_token_hash TEXT,
  access_days INTEGER,
  access_type TEXT DEFAULT 'vip',
  -- Dados do comprador. O CPF/CNPJ NÃO é guardado inteiro: fica o hash (para
  -- conciliar com a SigiloPay) e os 3 últimos dígitos (para suporte). Telefone
  -- e e-mail ficam porque são o contato do cliente depois da compra.
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  customer_document_hash TEXT,
  customer_document_last3 TEXT,
  created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'utc'),
  paid_at TIMESTAMP,
  expires_at TIMESTAMP,
  metadata TEXT
);

CREATE TABLE IF NOT EXISTS entitlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  telegram_user_id TEXT,
  product_id TEXT NOT NULL,
  starts_at TIMESTAMP,
  expires_at TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS access_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  token_hash TEXT NOT NULL,
  used_at TIMESTAMP,
  expires_at TIMESTAMP,
  telegram_user_id TEXT,
  created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'utc')
);

-- Espelha a tabela que a migração do SQLite cria para não perder histórico.
CREATE TABLE IF NOT EXISTS entitlement_duplicates_archive (
  LIKE entitlements,
  archived_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'utc')
);

-- As mesmas garantias do SQLite, e é delas que vem a idempotência:
-- um entitlement por pedido, um webhook_token por pedido, um checkout por pedido.
CREATE UNIQUE INDEX IF NOT EXISTS entitlement_order_unique ON entitlements(order_id);
CREATE UNIQUE INDEX IF NOT EXISTS webhook_token_unique ON orders(webhook_token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS checkout_hash_unique ON orders(checkout_hash);
CREATE UNIQUE INDEX IF NOT EXISTS provider_payment_unique ON orders(payment_provider, provider_payment_id);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);
CREATE INDEX IF NOT EXISTS access_tokens_hash_idx ON access_tokens(token_hash);
